### Data analysis of the Strathclyde REFIT data

A notebook which demonstrates analysis of the Strathclyde dataset

#### Setup

In [12]:
import pandas as pd
from pandas import *
import os
filepath=r'C:\Users\cvcs4\OneDrive - Loughborough University\Data Analysis\Refit\Clean House'
## r infront of '' means the string is raw - you need this if it's a 
## filepath because backspaces do funny things to the 
## string if you don't tell python it's raw.
## The above filepath is for the folder containing the files.

### Data processing

This loads the data, resamples it to half hour intervals and saves the raw data files.
We need to loop through files in a directory (a directory is a folder).

In [23]:
flag=True
for filename in os.listdir(filepath):
    print(filename)
    path=os.path.join(filepath,filename)
    ## the above needs doing because the filepath is not in the same
    ## folder that we're working in here
    
    ## parse_dates=['Time'] is a better way of getting the time column to work
    df=pd.read_csv(path,parse_dates=['Time'])
    
    ## set index as time column
    df=df.set_index('Time')
    
    ## resample the data to work with half hour intervals
    ## T = minutes, M=monthly
    df=df.resample('30T').mean()
    
    ## remove time from index and set it to 0,1,2 etc
    df=df.reset_index()
    
    ## create a column showing the filename
    df['file']=filename
    
    ## This flag function makes it add each file's dataframe to the last (append)
    ## This will be useful! See the flag=True at the top of the loop
    if flag:
        df2=df
        flag=False
    else:
        df2=df2.append(df)
    
    ## For the sake of seeing if everything works, break breaks the loop.
    ## Femove this when you want to run the entire loop.
    # break
    
    ## Save the data extracted and appended (above) to a new massive file
    ## containing all the data from the files in the folder.
df2.to_csv('NewData.csv')

CLEAN_House1.csv
CLEAN_House10.csv
CLEAN_House2.csv
CLEAN_House3.csv
CLEAN_House4.csv
CLEAN_House5.csv
CLEAN_House6.csv
CLEAN_House7.csv
CLEAN_House8.csv
CLEAN_House9.csv

In [24]:
df2.head()

,Time,Unix,Aggregate,Appliance1,Appliance2,Appliance3,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,Issues,file
0,2013-10-09 13:00:00,1.381325e+09,1443.930736,38.961039,7.506494,5.086580,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,CLEAN_House1.csv
1,2013-10-09 13:30:00,1.381326e+09,601.003367,0.000000,27.562290,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,CLEAN_House1.csv
2,2013-10-09 14:00:00,1.381328e+09,937.972881,0.206780,17.962712,68.718644,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,CLEAN_House1.csv
3,2013-10-09 14:30:00,1.381330e+09,350.345196,5.615658,18.455516,13.512456,0.0,0.0,0.0,0.0,0.0,1.0,0.003559,CLEAN_House1.csv
4,2013-10-09 15:00:00,1.381332e+09,423.656463,70.704082,28.840136,5.891156,0.0,0.0,0.0,0.0,0.0,1.0,0.006803,CLEAN_House1.csv